### ISSUE TITLE
How to setup a Github bot for comment in PR

### ISSUE THREAD

**Issue by manhdung20112000** [py-actions/flake8#110]
Hi, can I ask how to setup `flake8` actions with Github bot comment for error in PR like show below:

![image](https://user-images.githubusercontent.com/48562727/141412567-fa07a5b5-2e47-4bc2-9907-074002e5c5f6.png)

**Comment by chrissimpkins** [comment]
I believe that this can be done with [actions/core annotations](https://github.com/actions/toolkit/tree/main/packages/core#annotations).

**Comment by chrissimpkins** [comment]
Please let me know if there is anything else that I can do! Feel free to reopen if you have any other questions.
