### ISSUE TITLE
The process '/grid/0/jenkins/.local/bin/flake8' failed with exit code 1

### ISSUE THREAD

**Issue by swathida-byte** [py-actions/flake8#171]
<img width="849" alt="Screenshot 2022-08-16 at 6 31 18 PM" src="https://user-images.githubusercontent.com/97519234/184885981-2c77de9e-bf42-404d-a261-d4f36796e629.png">
Its listing all errors in the file and later it exits with this error "The process '/grid/0/jenkins/.local/bin/flake8' failed with exit code 1"

**Comment by chrissimpkins** [comment]
This appears to be working as intended.  Flake8 will raise a non-zero exit status code when there are identified lint issues and this fails your CI test suite.  Am I missing a problem in the execution here?

**Comment by swathida-byte** [comment]
what will be the output because it says none in Readme , will it comment on the actions tab or it just shows errors in logs??

**Comment by swathida-byte** [comment]
so when there are lint issues it comments with failed with exit code 1?

**Comment by chrissimpkins** [comment]
That is correct.  The report is in the output on the Actions page for a given workflow run.  This Action does not publish any information to the repository tracker or other locations.  If you provide context in your workflow naming (eg use the name “Python lints”) then you will see this as a line item in your pull request CI tests that are summarized at the bottom of the PR thread.
