### ISSUE TITLE
Unrecognized Arguments

### ISSUE THREAD

**Issue by seyyedaliayati** [py-actions/flake8#78]
I didn't set path like the default configuration but I got this error:
```bash
/opt/hostedtoolcache/Python/3.8.11/x64/bin/flake8 --ignore F403,F405, W503, W504 --exclude */migrations/* --max-line-length 120 .
usage: flake8 [options] file file ...
flake8: error: unrecognized arguments: .
Error: ERROR: Action failed during execution with error: The process '/opt/hostedtoolcache/Python/3.8.11/x64/bin/flake8' failed with exit code 2
```

Here is my yml file:
```yml
name: flake8 Lint # https://github.com/marketplace/actions/python-flake8-lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "120"
          exclude: "*/migrations/*"
          ignore: "F403,F405, W503, W504"

```

**Comment by chrissimpkins** [comment]
I think that it is the spaces in the ignore list.  Try removing all spaces inside the quotes

**Comment by mdcsaenz** [comment]
I had the same issue and I didnt have any spaces
`name: flake8 Lint # https://github.com/marketplace/actions/python-flake8-lint

on: [push, pull_request]
jobs:
    flake8-lint:
      runs-on: ubuntu-latest
      steps:
        - name: Check out source repository
          uses: actions/checkout@v2
        - name: Set up Python environment
          uses: actions/setup-python@v1
          with:
            python-version: "3.8"
        - name: flake8 Lint
          uses: py-actions/flake8@v1

**Comment by chrissimpkins** [comment]
I can reproduce the OP error locally when the spaces are present in the ignore option definitions.  It is eliminated when I remove the spaces (here with an existing local dir):

```
flake8 --ignore F403,F405,W503,W504 --exclude target --max-line-length 120 .
```

I think that removal of the spaces between the warning and fail codes should address your issue.

For @mdcsaenz issue, will you please post the error message that you receive when you execute that workflow?
